language: node_js

cache:
  directories:
    - node_modules
    - "~/.npm"

node_js:
  - "16"

services:
  - docker

git:
  depth: 3

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t jochizan/cnn-server -f dockerfile.prod .
  - docker tag jochizan/cnn-server:latest jochizan/cnn-server:v1
  - docker tag jochizan/cnn-server:v1 registry.heroku.com/$HEROKU_APP_CNN/web

notifications:
  slack:
    secure: "xDqu5kkMGp5upbPVbFYPXccOs/CYk30lQ6z+m6DkraRgEZVWIge5lqs38KtlGxBiOHGLkr+f+VNKfFYlUBoJOpP2JZcuiiA5JPGRWs02/DO/5RhdUot+2/6mm4IPeN9fSi/z9ncLEnMsW8KPfwpIAgYxmZaIIwuKfvbkvcj0C8nvgLUF6LV+9OdmIjbNYogbq/Pe73V0uRzDChGvg+eIouUUu/enp73QfG8itvEH8rX29b4h8nkxj21EJANWqL8iC4TTFVI0iHCIc4iRg2O0tr7VVASRHxgh4BcWo+pVLUfYkcuPv861GsHQkE+sDHbJ+s5y2ziulYbamgSqte6J87roAagRzR9l5Di2ZwjCDuQaOjsk5SWLWl811tXtr+aVwtGdHplCqHFZ+IypC64zcOwDnoJ08Le5BERxU6947ZCsqnbmw54rJKT+gqPKr+6PHq+JsoRdE1sOGeLXP/xfDuMwTRNJnAI36+1JBBBRBkUI9OjsvsZ6YW9GT04440VGOl/JIqCLSBbqGAhJyB/ojI4B9m/973Ecr9MMxk+qiw5ZQHRgVPkDHRyNhSmMiEMzP5t3XC34qm0RF36iP+ANBFhkeQzUUpNF2KNm7iJQzifgvnGLOJnbXeuHY1nF0jFMhCuym+8ydOsQLOA0QOJH3NR4abpgenjndTc4lO15iaA="
  email:
    recipients:
      - jochizan.apps40@gmail.com
    on_success: always

deploy:
  provider: script
  script: docker push jochizan/cnn-server:v1;
    docker push registry.heroku.com/$HEROKU_APP_CNN/web;
    heroku container:release web --app $HEROKU_APP_CNN
  on:
    repo: tiquor/cnn-server
    branch: master
